POST http://localhost:3001/api/dataklean/login
Content-Type: application/json


{
    "email":"pilipus@gmail.com",
    "password":"Pilipus123."
    
}
###

GET http://localhost:3001/Listuser
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mjg4NTIxYmM5MWU2MmFlNzkzZDQwYmQiLCJpYXQiOjE2NTMyMDQ2ODMsImV4cCI6MTY1MzgwOTQ4M30.zDoWybV6h4I7RRr6vkCDFh71dR1Ie9ev_TLXqCjQ3CU
###

GET http://localhost:3001/profile
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mjg4NTIxYmM5MWU2MmFlNzkzZDQwYmQiLCJpYXQiOjE2NTMyMDQ2ODMsImV4cCI6MTY1MzgwOTQ4M30.zDoWybV6h4I7RRr6vkCDFh71dR1Ie9ev_TLXqCjQ3CU
###

DELETE http://localhost:3001/profile
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mjg4NTIxYmM5MWU2MmFlNzkzZDQwYmQiLCJpYXQiOjE2NTMyMDQ2ODMsImV4cCI6MTY1MzgwOTQ4M30.zDoWybV6h4I7RRr6vkCDFh71dR1Ie9ev_TLXqCjQ3CU
###
POST  http://localhost:3001/tokenisValid
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mjg4NTIxYmM5MWU2MmFlNzkzZDQwYmQiLCJpYXQiOjE2NTMyMDQ2ODMsImV4cCI6MTY1MzgwOTQ4M30.zDoWybV6h4I7RRr6vkCDFh71dR1Ie9ev_TLXqCjQ3CU
###

GET http://localhost:3001/api/dataklean